#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    using Microsoft.Web.WebPages.OAuth;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class ExternalLoginsListPartial : System.Web.Mvc.WebViewPage<ICollection<AuthenticationClientData>>
    {
        public ExternalLoginsListPartial()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 if (Model.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"message-info\"");

WriteLiteral(">\r\n        <p>未配置外部身份验证服务。请参见<a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=252166\"");

WriteLiteral(">此文章</a>，\r\n        以详细了解如何将此 ASP.NET 应用程序设置为支持通过外部服务登录。</p>\r\n    </div>\r\n");

            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
}
else
{
    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
    {
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <fieldset");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <legend>使用其他服务登录</legend>\r\n        <p>\r\n");

            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
         foreach (AuthenticationClientData p in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 606), Tuple.Create("\"", 650)
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 614), Tuple.Create<System.Object, System.Int32>(p.AuthenticationClient.ProviderName
            
            #line default
            #line hidden
, 614), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 651), Tuple.Create("\"", 683)
, Tuple.Create(Tuple.Create("", 659), Tuple.Create("使用你的", 659), true)
            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                           , Tuple.Create(Tuple.Create(" ", 663), Tuple.Create<System.Object, System.Int32>(p.DisplayName
            
            #line default
            #line hidden
, 664), false)
, Tuple.Create(Tuple.Create(" ", 678), Tuple.Create("帐户登录", 679), true)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                                                           Write(p.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 21 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n    </fieldset>\r\n");

            
            #line 24 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
