#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ExternalLoginConfirmation.cshtml")]
    public partial class ExternalLoginConfirmation : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.RegisterExternalLoginModel>
    {
        public ExternalLoginConfirmation()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
  
    ViewBag.Title = "注册";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 7 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>关联你的 ");

            
            #line 8 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
        Write(ViewBag.ProviderDisplayName);

            
            #line default
            #line hidden
WriteLiteral(" 帐户。</h2>\r\n</hgroup>\r\n\r\n");

            
            #line 11 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
 using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl })) {
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>关联表单</legend>\r\n        <p>\r\n            你已成功地使用 <" +
"strong>");

            
            #line 18 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                       Write(ViewBag.ProviderDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</strong> 进行身份验证。\r\n            请在下面输入此站点的用户名，然后单击“确认”按钮完成\r\n            登录。\r\n     " +
"   </p>\r\n        <ol>\r\n            <li");

WriteLiteral(" class=\"name\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.LabelFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.TextBoxFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
           Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n        </ol>\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(Html.HiddenFor(m => m.ExternalLoginData));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"注册\"");

WriteLiteral(" />\r\n    </fieldset>\r\n");

            
            #line 32 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
