#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.ManagerMent
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ManagerMent/AboutUs.cshtml")]
    public partial class AboutUs : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.AboutUsModel>
    {
        public AboutUs()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ManagerMent\AboutUs.cshtml"
  
    ViewBag.Title = "关于我们";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>\r\n    AboutUs</h2>\r\n<fieldset>\r\n    <legend>关于我们</legend>\r\n    <div");

WriteLiteral(" class=\"display-label\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\Admin\Views\ManagerMent\AboutUs.cshtml"
   Write(Html.DisplayNameFor(model => model.Coment));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"display-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\Admin\Views\ManagerMent\AboutUs.cshtml"
   Write(Html.DisplayTextFor(model => model.Coment));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"prew\"");

WriteLiteral(">\r\n    </div>\r\n</fieldset>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\Admin\Views\ManagerMent\AboutUs.cshtml"
Write(Html.ActionLink("编辑更新", "EditAboutUs", new { id = Model.ID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\Admin\Views\ManagerMent\AboutUs.cshtml"
Write(Html.ActionLink("返回主页", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
