#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.ManagerMent
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ManagerMent/EditAboutUs.cshtml")]
    public partial class EditAboutUs : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.AboutUsModel>
    {
        public EditAboutUs()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
  
    ViewBag.Title = "编辑关于我们";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
   Write(Html.HiddenFor(model => model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
       Write(Html.LabelFor(model => model.Coment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(" style=\"width: 900px;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
       Write(Html.TextAreaFor(entity => entity.Coment));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <p>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"保存\"");

WriteLiteral(" />\r\n        </p>\r\n    </fieldset>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Html.ActionLink("返回", "AboutUs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Scripts.Render("~/Areas/Admin/Scripts/ueditor/ueditor.all.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Scripts.Render("~/Areas/Admin/Scripts/ueditor/ueditor.all.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Scripts.Render("~/Areas/Admin/Scripts/ueditor/ueditor.config.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Areas\Admin\Views\ManagerMent\EditAboutUs.cshtml"
Write(Styles.Render("~/Areas/Admin/Scripts/ueditor/themes/iframe.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        $(function () {
            var editor = new baidu.editor.ui.Editor({
                UEDITOR_HOME_URL: '/Areas/Admin/Scripts/ueditor/', //配置编辑器路径
                iframeCssUrl: '/Areas/Admin/Scripts/ueditor/themes/iframe.css', //样式路径
                initialContent: '欢迎使用ueditor', //初始化编辑器内容
                autoHeightEnabled: false, //高度自动增长
                minFrameHeight: 500, //最小高度
                initialFrameHeight: 580//初始化编辑器高度

            });
            editor.render('Coment');

        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
