#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.ManagerMent
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 2 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ManagerMent/ImageManager.cshtml")]
    public partial class ImageManager : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.ImageModel>
    {
        public ImageManager()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
  
    ViewBag.Title = "图片管理";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
 using (Html.BeginForm("ImageManager", "ManagerMent", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
                                 
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
Write(Html.HiddenFor(entity => entity.ID));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("    <table>\r\n        <tr>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
           Write(Html.LabelFor(entity => entity.Title));

            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" style=\"color: Red;\"");

WriteLiteral(">*</span>\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
           Write(Html.TextBoxFor(entity => entity.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
           Write(Html.ValidationMessageFor(entity => entity.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
                                                      Write(Html.LabelFor(entity => entity.ImageType));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>");

            
            #line 25 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
           Write(Html.DropDownListFor(entity => entity.ImageType, new SelectList(Basicinfo.GetImageTypeList(), "ImageType", "ImageName")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">\r\n                图片路径\r\n            </td>\r\n            <td>\r\n                ");

WriteLiteral("\r\n                <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"uploadfile\"");

WriteLiteral(" name=\"uploadfile\"");

WriteLiteral(" onchange=\"c(this)\"");

WriteLiteral(" style=\"width: 300px;\"");

WriteLiteral(" />\r\n                &nbsp; <span");

WriteLiteral(" style=\"color: Red; line-height: 27px; height: 27px;\"");

WriteLiteral(">添加图片</span>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

WriteLiteral("    <fieldset");

WriteLiteral(" style=\"width: 572; height: 100; padding: 2px;\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n    </fieldset>\r\n");

WriteLiteral("    <div>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" id=\"UploadButton\"");

WriteLiteral(" onclick=\"checkImg()\"");

WriteLiteral(" />\r\n    </div>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
    
}

            
            #line default
            #line hidden
DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 48 "..\..\Areas\Admin\Views\ManagerMent\ImageManager.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        UpLoadFileCheck = function () {\r\n            this.AllowExt = \".jpg,.gi" +
"f,.bmp,.png\"; //允许上传的文件类型 0为无限制      \r\n            this.AllowImgFileSize = 0; //" +
"允许上传文件的大小 0为无限制 单位：KB      \r\n            this.AllowImgWidth = 300; //允许上传的图片的宽度 " +
"0为无限制　单位：px      \r\n            this.AllowImgHeight = 300; //允许上传的图片的高度 0为无限制　单位：" +
"px      \r\n            this.ImgObj = new Image();\r\n            this.ImgFileSize =" +
" 0;\r\n            this.ImgWidth = 0;\r\n            this.ImgHeight = 0;\r\n          " +
"  this.FileExt = \"\";\r\n            this.ErrMsg = \"\";\r\n            this.IsImg = fa" +
"lse;\r\n\r\n        }\r\n\r\n        UpLoadFileCheck.prototype.CheckExt = function (obj)" +
" {\r\n            this.ErrMsg = \"\";\r\n            this.ImgObj.src = obj.value;\r\n   " +
"         if (obj.value == \"\") {\r\n                this.ErrMsg = \"\\n请选择一个文件\";\r\n   " +
"         }\r\n            else {\r\n                this.FileExt = obj.value.substr(" +
"obj.value.lastIndexOf(\".\")).toLowerCase();\r\n                if (this.AllowExt !=" +
" 0 && this.AllowExt.indexOf(this.FileExt) == -1) {\r\n                    this.Err" +
"Msg = \"\\n该文件类型不允许上传\";\r\n                }\r\n            }\r\n            if (this.Er" +
"rMsg != \"\") {\r\n                this.ShowMsg(this.ErrMsg, false);\r\n              " +
"  return false;\r\n            }\r\n            else\r\n                return this.Ch" +
"eckProperty(obj);\r\n        }\r\n\r\n        UpLoadFileCheck.prototype.CheckProperty " +
"= function (obj) {\r\n            if (this.IsImg == true) {\r\n                this." +
"ImgWidth = this.ImgObj.width;\r\n                this.ImgHeight = this.ImgObj.heig" +
"ht;\r\n                if (this.AllowImgWidth != 0 && this.AllowImgWidth < this.Im" +
"gWidth)\r\n                    this.ErrMsg = this.ErrMsg + \"\\n图片宽度超过限制。请上传宽度小于\" + " +
"this.AllowImgWidth + \"px的文件\";\r\n\r\n                if (this.AllowImgHeight != 0 &&" +
" this.AllowImgHeight < this.ImgHeight)\r\n                    this.ErrMsg = this.E" +
"rrMsg + \"\\n图片高度超过限制。请上传高度小于\" + this.AllowImgHeight + \"px的文件\";\r\n            }\r\n\r\n" +
"            this.ImgFileSize = Math.round(this.ImgObj.fileSize / 1024 * 100) / 1" +
"00;\r\n            if (this.AllowImgFileSize != 0 && this.AllowImgFileSize < this." +
"ImgFileSize)\r\n                this.ErrMsg = this.ErrMsg + \"\\n文件大小超过限制。请上传小于\" + t" +
"his.AllowImgFileSize + \"KB的文件\";\r\n\r\n            if (this.ErrMsg != \"\") {\r\n       " +
"         this.ShowMsg(this.ErrMsg, false);\r\n                return false;\r\n     " +
"       }\r\n            else\r\n                return true;\r\n        }\r\n\r\n        U" +
"pLoadFileCheck.prototype.ShowMsg = function (msg, tf) {\r\n            alert(msg);" +
"\r\n        }\r\n\r\n        function c(obj) {\r\n            var d = new UpLoadFileChec" +
"k();\r\n            d.IsImg = true;\r\n            d.AllowImgFileSize = 1;\r\n        " +
"    d.CheckExt(obj)\r\n        }  \r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
