#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Business
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.BusinessModel>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Business\Detail.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutBusiness.cshtml";
    var list = Model.Weds.ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 252), Tuple.Create("\"", 286)
, Tuple.Create(Tuple.Create("", 258), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/title_b.png")
, 258), false)
);

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 452), Tuple.Create("\"", 483)
, Tuple.Create(Tuple.Create("", 458), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 458), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 570), Tuple.Create("\"", 604)
            
            #line 16 "..\..\Views\Business\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 577), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 577), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 634), Tuple.Create("\"", 671)
, Tuple.Create(Tuple.Create("", 640), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 640), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 695), Tuple.Create("\"", 728)
            
            #line 18 "..\..\Views\Business\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 702), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Wed")
            
            #line default
            #line hidden
, 702), false)
);

WriteLiteral(">服务范围</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 760), Tuple.Create("\"", 797)
, Tuple.Create(Tuple.Create("", 766), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 766), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Business\Detail.cshtml"
           Write(Html.ActionLink("高端商务礼仪","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Business\Detail.cshtml"
               Write(Html.ActionLink("高端商务礼仪","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Business\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Business\Detail.cshtml"
                     foreach (var item in Model.Weds)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1331), Tuple.Create("\"", 1392)
            
            #line 32 "..\..\Views\Business\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1338), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "Business", new { id = item.ID})
            
            #line default
            #line hidden
, 1338), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Business\Detail.cshtml"
                                                                                                                Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 34 "..\..\Views\Business\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_wed_detail_body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_wed_detail_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Views\Business\Detail.cshtml"
                   Write(Model.Wed.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <hr />\r\n                    <di" +
"v");

WriteLiteral(" class=\"yc_wed_detail_body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Business\Detail.cshtml"
                   Write(Html.DisplayTextFor(t => t.Wed.NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
