#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.AboutUs
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AboutUs/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<YuanChen.Model.AboutUsTable>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\AboutUs\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 196), Tuple.Create("\"", 234)
, Tuple.Create(Tuple.Create("", 202), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/about_title.png")
, 202), false)
);

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 400), Tuple.Create("\"", 431)
, Tuple.Create(Tuple.Create("", 406), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 406), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 518), Tuple.Create("\"", 552)
            
            #line 15 "..\..\Views\AboutUs\Index.cshtml"
, Tuple.Create(Tuple.Create("", 525), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 525), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 582), Tuple.Create("\"", 619)
, Tuple.Create(Tuple.Create("", 588), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 588), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\AboutUs\Index.cshtml"
           Write(Html.ActionLink("关于我们","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_about_content_cont\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_right\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li><img");

WriteAttribute("src", Tuple.Create(" src=\"", 856), Tuple.Create("\"", 890)
, Tuple.Create(Tuple.Create("", 862), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/about_1.png")
, 862), false)
);

WriteLiteral(" /></li>\r\n                    <li><img");

WriteAttribute("src", Tuple.Create(" src=\"", 929), Tuple.Create("\"", 963)
, Tuple.Create(Tuple.Create("", 935), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/about_2.png")
, 935), false)
);

WriteLiteral(" /></li>\r\n                    <li><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1002), Tuple.Create("\"", 1036)
, Tuple.Create(Tuple.Create("", 1008), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/about_3.png")
, 1008), false)
);

WriteLiteral(" /></li>\r\n                </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_content_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_about_content_header\"");

WriteLiteral("><p>关于远辰/About Us</p></div>\r\n                <div");

WriteLiteral(" class=\"yc_about_content_body\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\AboutUs\Index.cshtml"
               Write(Html.DisplayTextFor(t => t.Coment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
