#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Offer
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Offer/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.NewsListViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Offer\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 223), Tuple.Create("\"", 260)
, Tuple.Create(Tuple.Create("", 229), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/news_title.png")
, 229), false)
);

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 426), Tuple.Create("\"", 457)
, Tuple.Create(Tuple.Create("", 432), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 432), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 544), Tuple.Create("\"", 578)
            
            #line 15 "..\..\Views\Offer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 551), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 551), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 608), Tuple.Create("\"", 645)
, Tuple.Create(Tuple.Create("", 614), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 614), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 669), Tuple.Create("\"", 703)
            
            #line 17 "..\..\Views\Offer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 676), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","News")
            
            #line default
            #line hidden
, 676), false)
);

WriteLiteral(">新闻动态</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 735), Tuple.Create("\"", 772)
, Tuple.Create(Tuple.Create("", 741), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 741), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Offer\Index.cshtml"
           Write(Html.ActionLink("优惠活动","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left yc_offer_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1022), Tuple.Create("\"", 1056)
            
            #line 25 "..\..\Views\Offer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1029), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","News")
            
            #line default
            #line hidden
, 1029), false)
);

WriteLiteral(">新闻动态</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1244), Tuple.Create("\"", 1278)
            
            #line 29 "..\..\Views\Offer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1251), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","News")
            
            #line default
            #line hidden
, 1251), false)
);

WriteLiteral(">公司动态</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_news_right_1\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"i_selected\"");

WriteLiteral(">></i>");

            
            #line 32 "..\..\Views\Offer\Index.cshtml"
                                              Write(Html.ActionLink("优惠活动","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"yc_news_right yc_offer_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_offer_right_body\"");

WriteLiteral(">\r\n                    <ul>\r\n");

            
            #line 39 "..\..\Views\Offer\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Offer\Index.cshtml"
                         foreach (var news in Model.News)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <div");

WriteLiteral(" class=\"yc_offer_container\"");

WriteLiteral(">\r\n                                    <div>\r\n                                   " +
"     <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1930), Tuple.Create("\"", 1959)
, Tuple.Create(Tuple.Create("", 1937), Tuple.Create("/Offer/Detail/", 1937), true)
            
            #line 44 "..\..\Views\Offer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1951), Tuple.Create<System.Object, System.Int32>(news.ID
            
            #line default
            #line hidden
, 1951), false)
);

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1965), Tuple.Create("\"", 1998)
            
            #line 44 "..\..\Views\Offer\Index.cshtml"
   , Tuple.Create(Tuple.Create("", 1971), Tuple.Create<System.Object, System.Int32>(Url.Content(news.ImageUrl)
            
            #line default
            #line hidden
, 1971), false)
);

WriteLiteral(" style=\"width:316px;height:200px;\"");

WriteLiteral(" /></a>\r\n                                    </div>\r\n");

WriteLiteral("                                    ");

            
            #line 46 "..\..\Views\Offer\Index.cshtml"
                               Write(Html.ActionLink(news.Title, "Detail", new { id = news.ID,@class="yc_detail_title"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </li>\r\n");

            
            #line 49 "..\..\Views\Offer\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                    <div");

WriteLiteral(" class=\"yc_offer_clear\"");

WriteLiteral(">.</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 55 "..\..\Views\Offer\Index.cshtml"
               Write(Html.PageLinks(Model.NewsInfo, x => Url.Action("Index", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
