#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.CarService
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 2 "..\..\Views\CarService\CarServiceDetails.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CarService/CarServiceDetails.cshtml")]
    public partial class CarServiceDetails : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.News_ServiceInfoListViewModel>
    {
        public CarServiceDetails()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\CarService\CarServiceDetails.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutBusiness.cshtml";
    var list = Model.NewsServiceInfo.ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\CarService\CarServiceDetails.cshtml"
  
    var serverlist = Basicinfo.GetTopServerListCar();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 385), Tuple.Create("\"", 421)
, Tuple.Create(Tuple.Create("", 391), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/carserver.png")
, 391), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 588), Tuple.Create("\"", 619)
, Tuple.Create(Tuple.Create("", 594), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 594), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 706), Tuple.Create("\"", 741)
            
            #line 19 "..\..\Views\CarService\CarServiceDetails.cshtml"
, Tuple.Create(Tuple.Create("", 713), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 713), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 771), Tuple.Create("\"", 808)
, Tuple.Create(Tuple.Create("", 777), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 777), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\CarService\CarServiceDetails.cshtml"
           Write(Html.ActionLink("服务范围", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 885), Tuple.Create("\"", 922)
, Tuple.Create(Tuple.Create("", 891), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 891), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\CarService\CarServiceDetails.cshtml"
           Write(Html.ActionLink("高端汽车服务", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left  yc_pledge_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\CarService\CarServiceDetails.cshtml"
               Write(Html.ActionLink("高端汽车服务", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\CarService\CarServiceDetails.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\CarService\CarServiceDetails.cshtml"
                     if (serverlist != null && serverlist.Count > 0)
                    {
                        foreach (var item in serverlist)
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1574), Tuple.Create("\"", 1653)
            
            #line 37 "..\..\Views\CarService\CarServiceDetails.cshtml"
, Tuple.Create(Tuple.Create("", 1581), Tuple.Create<System.Object, System.Int32>(Url.Action("CarServiceDetails", "CarService", new { id = item.ListID })
            
            #line default
            #line hidden
, 1581), false)
);

WriteLiteral(">");

            
            #line 37 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                                                                                                                  Write(item.ListName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 39 "..\..\Views\CarService\CarServiceDetails.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right yc_pledge_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_body\"");

WriteLiteral(">\r\n                    <ul>\r\n");

            
            #line 46 "..\..\Views\CarService\CarServiceDetails.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\CarService\CarServiceDetails.cshtml"
                         for (var i = 0; i < list.Count; i++)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <div");

WriteLiteral(" class=\"yc_wed_container\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"yc_wed_body\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"yc_wed_img\"");

WriteLiteral(">\r\n");

            
            #line 52 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                             if (!string.IsNullOrEmpty(list[i].ImageUrl))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2439), Tuple.Create("\"", 2492)
            
            #line 54 "..\..\Views\CarService\CarServiceDetails.cshtml"
, Tuple.Create(Tuple.Create("", 2446), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", new { id = list[i].ID })
            
            #line default
            #line hidden
, 2446), false)
);

WriteLiteral(">\r\n                                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2552), Tuple.Create("\"", 2588)
            
            #line 55 "..\..\Views\CarService\CarServiceDetails.cshtml"
, Tuple.Create(Tuple.Create("", 2558), Tuple.Create<System.Object, System.Int32>(Url.Content(list[i].ImageUrl)
            
            #line default
            #line hidden
, 2558), false)
);

WriteLiteral(" style=\"width:275px;height:190px;\"");

WriteLiteral(" />\r\n                                                </a>\r\n");

            
            #line 57 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <a>无图片</a> \r\n");

            
            #line 61 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n                                 " +
"       <div");

WriteLiteral(" class=\"yc_wed_content\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"yc_wed_content_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 65 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                           Write(Html.ActionLink(list[i].TiTle, "Detail", new { id = list[i].ID, @class = "yc_wed_content_title" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </div>\r\n                           " +
"                 <div");

WriteLiteral(" class=\"yc_wed_content_body\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 68 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                           Write(Html.DisplayTextFor(entiy => list[i].NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </div>\r\n                           " +
"                 <div");

WriteLiteral(" class=\"yc_wed_content_detail\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 71 "..\..\Views\CarService\CarServiceDetails.cshtml"
                                           Write(Html.ActionLink(">> 点击查看套餐详细", "Detail", new { id = list[i].ID, @class = "yc_wed_detail_link" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </div>\r\n                           " +
"             </div>\r\n                                    </div>\r\n               " +
"                 </div>\r\n                            </li>\r\n");

            
            #line 77 "..\..\Views\CarService\CarServiceDetails.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">\r\n                    .</div>\r\n                <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Views\CarService\CarServiceDetails.cshtml"
               Write(Html.PageLinks(Model.NewsInfo, x => Url.Action("CarServiceDetails", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r" +
"\n");

        }
    }
}
#pragma warning restore 1591
