#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.CarService
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 2 "..\..\Views\CarService\Detail.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CarService/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<YuanChen.Model.News_info>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\CarService\Detail.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\CarService\Detail.cshtml"
  
    var list = Basicinfo.GetTopServerListCar();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 282), Tuple.Create("\"", 318)
, Tuple.Create(Tuple.Create("", 288), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/carserver.png")
, 288), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 485), Tuple.Create("\"", 516)
, Tuple.Create(Tuple.Create("", 491), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 491), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 603), Tuple.Create("\"", 638)
            
            #line 18 "..\..\Views\CarService\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 610), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 610), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 668), Tuple.Create("\"", 705)
, Tuple.Create(Tuple.Create("", 674), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 674), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\CarService\Detail.cshtml"
           Write(Html.ActionLink("服务范围", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 782), Tuple.Create("\"", 819)
, Tuple.Create(Tuple.Create("", 788), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 788), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\CarService\Detail.cshtml"
           Write(Html.ActionLink("高端汽车服务", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\CarService\Detail.cshtml"
               Write(Html.ActionLink("高端汽车服务", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\CarService\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\CarService\Detail.cshtml"
                     if (list != null && list.Count > 0)
                    {
                        foreach (var item in list)
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">●</i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1437), Tuple.Create("\"", 1516)
            
            #line 36 "..\..\Views\CarService\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1444), Tuple.Create<System.Object, System.Int32>(Url.Action("CarServiceDetails", "CarService", new { id = item.ListID })
            
            #line default
            #line hidden
, 1444), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Views\CarService\Detail.cshtml"
                                                                                                                                  Write(item.ListName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 38 "..\..\Views\CarService\Detail.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_detail_right_body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_detail_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\CarService\Detail.cshtml"
                   Write(Model.TiTle);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_detail_time\"");

WriteLiteral(">\r\n                        发布时间： ");

            
            #line 48 "..\..\Views\CarService\Detail.cshtml"
                         Write(Model.Time.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 50 "..\..\Views\CarService\Detail.cshtml"
               Write(Html.DisplayTextFor(t => t.NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">\r\n                .</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
