#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public partial class About : System.Web.Mvc.WebViewPage<dynamic>
    {
        public About()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\About.cshtml"
  
    ViewBag.Title = "关于";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Home\About.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>");

            
            #line 7 "..\..\Views\Home\About.cshtml"
   Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral(@"</h2>
</hgroup>

<article>
    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>
</article>

<aside>
    <h3>副标题</h3>
    <p>
        使用此区域可提供附加信息。
    </p>
    <ul>
        <li>");

            
            #line 30 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("主页", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 31 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("关于", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 32 "..\..\Views\Home\About.cshtml"
       Write(Html.ActionLink("联系方式", "Contact", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n</aside>");

        }
    }
}
#pragma warning restore 1591
