#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Contact.cshtml")]
    public partial class Contact : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Contact()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "联系方式";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Home\Contact.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n    <h2>");

            
            #line 7 "..\..\Views\Home\Contact.cshtml"
   Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</hgroup>\r\n\r\n<section");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>电话</h3>\r\n    </header>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">主要:</span>\r\n        <span>425.555.0100</span>\r\n    </p>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">下班后:</span>\r\n        <span>425.555.0199</span>\r\n    </p>\r\n</section>\r\n\r\n<section" +
"");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>电子邮件</h3>\r\n    </header>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">支持:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:Support@example.com\"");

WriteLiteral(">Support@example.com</a></span>\r\n    </p>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">营销:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:Marketing@example.com\"");

WriteLiteral(">Marketing@example.com</a></span>\r\n    </p>\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"label\"");

WriteLiteral(">常规:</span>\r\n        <span><a");

WriteLiteral(" href=\"mailto:General@example.com\"");

WriteLiteral(">General@example.com</a></span>\r\n    </p>\r\n</section>\r\n\r\n<section");

WriteLiteral(" class=\"contact\"");

WriteLiteral(">\r\n    <header>\r\n        <h3>地址</h3>\r\n    </header>\r\n    <p>\r\n        One Microso" +
"ft Way<br />\r\n        Redmond, WA 98052-6399\r\n    </p>\r\n</section>");

        }
    }
}
#pragma warning restore 1591
