#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.IndexModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "主页";
    var images = Model.Images.ToList();
    var news = Model.News.ToList();
    var service = Model.Service.ToList();
    var content = string.Empty;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"wowslider-container1\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ws_images\"");

WriteLiteral(">\r\n        <ul>\r\n");

            
            #line 12 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Home\Index.cshtml"
             for (int i = 0; i < images.Count; i++)
            {
                if (string.IsNullOrEmpty(images[i].LinkUrl))
                {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 503), Tuple.Create("\"", 542)
            
            #line 17 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 509), Tuple.Create<System.Object, System.Int32>(Url.Content(images[i].ImagerUrl)
            
            #line default
            #line hidden
, 509), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 543), Tuple.Create("\"", 556)
, Tuple.Create(Tuple.Create("", 548), Tuple.Create("wows1_", 548), true)
            
            #line 17 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 554), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 554), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 557), Tuple.Create("\"", 579)
            
            #line 17 "..\..\Views\Home\Index.cshtml"
     , Tuple.Create(Tuple.Create("", 563), Tuple.Create<System.Object, System.Int32>(images[i].Title
            
            #line default
            #line hidden
, 563), false)
);

WriteLiteral("/>\r\n                </li>\r\n");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 689), Tuple.Create("\"", 714)
            
            #line 22 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 696), Tuple.Create<System.Object, System.Int32>(images[i].LinkUrl
            
            #line default
            #line hidden
, 696), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 758), Tuple.Create("\"", 797)
            
            #line 23 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 764), Tuple.Create<System.Object, System.Int32>(Url.Content(images[i].ImagerUrl)
            
            #line default
            #line hidden
, 764), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 798), Tuple.Create("\"", 811)
, Tuple.Create(Tuple.Create("", 803), Tuple.Create("wows1_", 803), true)
            
            #line 23 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 809), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 809), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 812), Tuple.Create("\"", 834)
            
            #line 23 "..\..\Views\Home\Index.cshtml"
     , Tuple.Create(Tuple.Create("", 818), Tuple.Create<System.Object, System.Int32>(images[i].Title
            
            #line default
            #line hidden
, 818), false)
);

WriteLiteral("/>\r\n                </a></li>\r\n");

            
            #line 25 "..\..\Views\Home\Index.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n        </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ws_bullets\"");

WriteLiteral(">\r\n        <div>\r\n");

            
            #line 36 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Home\Index.cshtml"
             for (int i = 0; i < images.Count; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Home\Index.cshtml"
                       Write(i);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 39 "..\..\Views\Home\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"yc_bottom_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_bottom_news\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_bottom_news_title\"");

WriteLiteral(">\r\n            <p>\r\n                新闻动态/News</p>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_bottom_news_content\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"yc_bottom_news_ul\"");

WriteLiteral(">\r\n");

            
            #line 56 "..\..\Views\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Home\Index.cshtml"
                 for (var n = 0; n < @news.Count; n++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2078), Tuple.Create("\"", 2139)
            
            #line 58 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2085), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "News", new { id = news[n].ID })
            
            #line default
            #line hidden
, 2085), false)
);

WriteLiteral(">");

            
            #line 58 "..\..\Views\Home\Index.cshtml"
                                                                                    Write(news[n].Title);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 59 "..\..\Views\Home\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_bottom_service\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_bottom_service_title\"");

WriteLiteral(">\r\n            <p>\r\n                服务范围/Service</p>\r\n        </div>\r\n        <di" +
"v");

WriteLiteral(" class=\"yc_bottom_service_content\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"yc_bottom_service_ul\"");

WriteLiteral(">\r\n");

            
            #line 70 "..\..\Views\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Home\Index.cshtml"
                 for (int s = 0; s < service.Count; s++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2582), Tuple.Create("\"", 2625)
            
            #line 72 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2589), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", service[s].Key)
            
            #line default
            #line hidden
, 2589), false)
);

WriteLiteral(">");

            
            #line 72 "..\..\Views\Home\Index.cshtml"
                                                                  Write(service[s].Value);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 73 "..\..\Views\Home\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_bottom_about\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_bottom_about_title\"");

WriteLiteral(">\r\n            <p>\r\n                关于远辰/About Us</p>\r\n        </div>\r\n        <d" +
"iv");

WriteLiteral(" class=\"yc_bottom_about_content\"");

WriteLiteral(">\r\n            <span>\r\n");

            
            #line 84 "..\..\Views\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Home\Index.cshtml"
                 if (Model.AboutUs.Coment.Length > 200)
                {
                    content = Model.AboutUs.Coment.Substring(0, 150) + "..."
                        + Html.ActionLink("更多", "Index", "AboutUs");
                }
                else
                {
                    content = Model.AboutUs.Coment + Html.ActionLink("更多", "Index");
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 93 "..\..\Views\Home\Index.cshtml"
           Write(Html.Raw(content));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_bottom_clear\"");

WriteLiteral(">\r\n        .</div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3500), Tuple.Create("\"", 3535)
, Tuple.Create(Tuple.Create("", 3506), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Slider/wowslider.js")
, 3506), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3578), Tuple.Create("\"", 3610)
, Tuple.Create(Tuple.Create("", 3584), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Slider/script.js")
, 3584), false)
);

WriteLiteral("></script>\r\n<link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3661), Tuple.Create("\"", 3694)
, Tuple.Create(Tuple.Create("", 3668), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Slider/style.css")
, 3668), false)
);

WriteLiteral(" />\r\n");

        }
    }
}
#pragma warning restore 1591
