#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.CustomerManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/CustomerManager/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.CustomerModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
  
    ViewBag.Title = "客户服务";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
    .table_custom
    {
        border: 1px solid #666;
        text-align: center;
    }

    td {
        border:1px solid #666;
        padding:3px;
    }
    .title
    {
        width: 100px;
        font-weight: bold;
    }
    
    .leirong
    {
        width: 180px;
    }
    div.back_to_list {
        margin-top:10px;
    }
</style>
<h2>
    客户服务</h2>
<div>
    <table");

WriteLiteral(" class=\"table_custom\"");

WriteLiteral(">\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"leirong\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"leirong\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"leirong\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 61 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"leirong\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 64 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 69 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 72 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 77 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayNameFor(model => model.FormatTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td");

WriteLiteral(" class=\"leirong\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 80 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
           Write(Html.DisplayFor(model => model.FormatTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</div>\r\n<div");

WriteLiteral(" class=\"back_to_list\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\Admin\Views\CustomerManager\Details.cshtml"
                     Write(Html.ActionLink("返回", "Index"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
