#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.CustomerManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/CustomerManager/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<MvcCarManagerment.Models.CustomerModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
  
    ViewBag.Title = "客户服务";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.info = "……";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .table td\r\n    {\r\n        text-align: center;\r\n    }\r\n</style>\r\n<h2");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">\r\n    客户服务列表</h2>\r\n<div");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n                    当前状态\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Time));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n                    操作\r\n                </th>\r\n            </tr>\r\n        </th" +
"ead>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" style=\"width: 30%\"");

WriteLiteral(">\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                     if (item.SubJect.Length > 20)
                    {
                        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                   Write(item.SubJect.Substring(0, 10));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                                                      
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                                                 Write(ViewBag.info);

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                                                                   
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                   Write(item.SubJect);

            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                                     
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td");

WriteLiteral(" style=\"width: 10%\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"width: 20%\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 56 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.DisplayFor(modelItem => item.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n");

            
            #line 58 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                 if (!item.IsRead)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"width: 10%; color: Red\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 61 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                   Write(item.IsReadStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 63 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"width: 10%\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 67 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                   Write(item.IsReadStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 69 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"width: 20%\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 71 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(item.FormatTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"width: 20%\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 74 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.ActionLink("查看", "Details", new { id = item.ID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                    ");

            
            #line 75 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
               Write(Html.ActionLink("删除", "Delete", new { id = item.ID }, new { onclick="return confirm('确认删除该条记录吗？')" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 78 "..\..\Areas\Admin\Views\CustomerManager\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
