#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Customer
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customer/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.CustomerModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Customer\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .title\r\n    {\r\n        text-align: center;\r\n        width: 20%;\r\n    }\r\n  " +
"  .btn\r\n    {\r\n        width: 100px;\r\n        height: 40px;\r\n    }\r\n</style>\r\n");

            
            #line 18 "..\..\Views\Customer\Index.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Customer\Index.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Customer\Index.cshtml"
                                 

    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n            <img");

WriteLiteral(" src=\"../../Content/images/con_title.png\"");

WriteLiteral(" />\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 780), Tuple.Create("\"", 811)
, Tuple.Create(Tuple.Create("", 786), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 786), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 902), Tuple.Create("\"", 937)
            
            #line 32 "..\..\Views\Customer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 909), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 909), false)
);

WriteLiteral(">首页</a>\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 971), Tuple.Create("\"", 1008)
, Tuple.Create(Tuple.Create("", 977), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 977), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Views\Customer\Index.cshtml"
               Write(Html.ActionLink("客户服务", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_customer_right\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_car_right_body\"");

WriteLiteral(">\r\n                        <table>\r\n                            <tr>\r\n           " +
"                     <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" class=\"title\"");

WriteLiteral(" style=\"font-size: 21px; font-weight: bold; padding-top: 30px\"");

WriteLiteral(">\r\n                                    欢迎通过在线留言联系我们，7x24小时为您服务！\r\n                " +
"                </td>\r\n                                <td");

WriteLiteral(" rowspan=\"8\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1634), Tuple.Create("\"", 1690)
            
            #line 46 "..\..\Views\Customer\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/images/customerright.png")
            
            #line default
            #line hidden
, 1640), false)
);

WriteLiteral(" />\r\n                                </td>\r\n                            </tr>\r\n  " +
"                          <tr>\r\n                                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" class=\"title\"");

WriteLiteral(" style=\"font-size: 14px;\"");

WriteLiteral(">\r\n                                    请务必填写完整，这样我们很快地了解你的需求并及时联系到您。\r\n           " +
"                     </td>\r\n                            </tr>\r\n                 " +
"           <tr>\r\n                                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 56 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.LabelFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 59 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.EditorFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 60 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.SubJect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 65 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.LabelFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 68 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.EditorFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 69 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 74 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.LabelFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 77 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.EditorFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 83 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.LabelFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 86 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.TextBoxFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 87 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Tel));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n     " +
"                       <tr>\r\n                                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 92 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.LabelFor(model => model.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n");

WriteLiteral("                                    ");

            
            #line 95 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.TextAreaFor(model => model.Comment, new { style = "height:70px;width:430px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 96 "..\..\Views\Customer\Index.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Comment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <font");

WriteLiteral(" color=\"red\"");

WriteLiteral(">至多输入500个字符</font>\r\n                                </td>\r\n                      " +
"      </tr>\r\n                            <tr>\r\n                                <" +
"td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"确定\"");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" style=\"padding:4px 14px;\"");

WriteLiteral(" />\r\n                                </td>\r\n                            </tr>\r\n  " +
"                      </table>\r\n                    </div>\r\n                </di" +
"v>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 111 "..\..\Views\Customer\Index.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 113 "..\..\Views\Customer\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            var msg = \'");

            
            #line 116 "..\..\Views\Customer\Index.cshtml"
                  Write(ViewData["msg"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            if (msg != \"\") {\r\n                alert(\'");

            
            #line 118 "..\..\Views\Customer\Index.cshtml"
                  Write(ViewData["msg"]);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n\r\n            }\r\n        });\r\n   \r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
