#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.News
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/News/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<YuanChen.Model.News>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\News\Detail.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 188), Tuple.Create("\"", 225)
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/news_title.png")
, 194), false)
);

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 391), Tuple.Create("\"", 422)
, Tuple.Create(Tuple.Create("", 397), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 397), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 509), Tuple.Create("\"", 543)
            
            #line 15 "..\..\Views\News\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 516), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 516), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 573), Tuple.Create("\"", 610)
, Tuple.Create(Tuple.Create("", 579), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 579), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\News\Detail.cshtml"
           Write(Html.ActionLink("新闻动态","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 686), Tuple.Create("\"", 723)
, Tuple.Create(Tuple.Create("", 692), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 692), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\News\Detail.cshtml"
           Write(Html.ActionLink("公司新闻","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\News\Detail.cshtml"
               Write(Html.ActionLink("新闻动态","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_news_right_1\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"i_selected\"");

WriteLiteral(">></i>");

            
            #line 29 "..\..\Views\News\Detail.cshtml"
                                              Write(Html.ActionLink("公司新闻","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1331), Tuple.Create("\"", 1366)
            
            #line 32 "..\..\Views\News\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1338), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Offer")
            
            #line default
            #line hidden
, 1338), false)
);

WriteLiteral(">优惠活动</a>\r\n                    </div>\r\n                </div>\r\n            </div>" +
"\r\n            <div");

WriteLiteral(" class=\"yc_news_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_detail_right_body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_detail_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Views\News\Detail.cshtml"
                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_detail_time\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 42 "..\..\Views\News\Detail.cshtml"
                   Write(Model.Time);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\News\Detail.cshtml"
               Write(Html.DisplayTextFor(t => t.NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
