#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.ImageManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ImageManager/EditImage.cshtml")]
    public partial class EditImage : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.ImageModel>
    {
        public EditImage()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
  
    ViewBag.Title = "编辑图片";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>编辑图片</h2>\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
                                 
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
Write(Html.HiddenFor(model => model.ID));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
Write(Html.HiddenFor(model => model.ImagerUrl));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
Write(Html.HiddenFor(model => model.ImageType));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
                                             
                                             

            
            #line default
            #line hidden
WriteLiteral("    <table>\r\n        <tr>\r\n            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                图像标题：\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
           Write(Html.TextBoxFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                图像链接：\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
           Write(Html.TextBoxFor(model => model.LinkUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td>\r\n             " +
"   <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"保存\"");

WriteLiteral(" class=\"btn btn_edit_submit\"");

WriteLiteral(" />\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
           Write(Html.ActionLink("返回", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

WriteLiteral("    <p>\r\n    </p>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Areas\Admin\Views\ImageManager\EditImage.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
