#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.ImageManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ImageManager/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.ImagesListViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
  
    ViewBag.Title = "图片管理列表";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int image_num = 0;
    var imagesList = Model.Images.ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>\r\n    首页图片管理列表</h2>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
Write(Html.ActionLink("增加图片", "AddImageManager", new { type = "1" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#image_view\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">首页图片</a></li>\r\n    ");

WriteLiteral("\r\n</ul>\r\n<div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"image_view\"");

WriteLiteral(" class=\" tab-pane active\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" style=\"width: 100%; border: 1px; text-align: center;\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
             for (int i = 0; i < 6; i++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                     for (; image_num < imagesList.Count; image_num++)
                    {
                        var item = imagesList[image_num];
                        i++; if (i == 4) { break; }

            
            #line default
            #line hidden
WriteLiteral("                        <td>\r\n                            <table>\r\n              " +
"                  <tr>\r\n                                    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                        图像标题： 【");

            
            #line 31 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                                          Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("】\r\n                                    </td>\r\n                                </t" +
"r>\r\n                                <tr>\r\n                                    <t" +
"d");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" src=");

WriteLiteral(" \"");

            
            #line 36 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                                              Write(Url.Content(@item.ImagerUrl));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width:200px; height:135px; border:0px;\" alt=\"");

            
            #line 36 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                                                                                                                                 Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                    </td>\r\n                                <" +
"/tr>\r\n                                <tr>\r\n                                    " +
"<td");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 41 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                                   Write(Html.ActionLink("编辑", "EditImage", new { id = item.ID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                                        ");

            
            #line 42 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                                   Write(Html.ActionLink("删除", "Delete", new { id = item.ID }, new { onclick = "return confirm('是否删除该图片');" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n                            </table>\r\n                        </td>\r\n");

            
            #line 47 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");

            
            #line 49 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
     
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n        <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 53 "..\..\Areas\Admin\Views\ImageManager\Index.cshtml"
       Write(Html.PageLinks(Model.NewsInfo, x => Url.Action("Index", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    ");

WriteLiteral("\r\n</div>\r\n<script");

WriteLiteral(" src=\"../../bundles/bootstrap-tab.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"../../bundles/bootstrap-transition.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        var log = function (s) {
            window.console && console.log(s)
        }
        $('.nav-tabs a:last').tab('show')
        $('a[data-toggle=""tab""]').on('show', function (e) {
            log(e);
            //            $(e.relatedTarget).removeClass(""active"");
            //            $(e.target).addClass(""active"");
        })
        $('a[data-toggle=""tab""]').on('shown', function (e) {
            log(e.target) // activated tab
            log(e.relatedTarget) // previous tab
        })
    })
</script>
");

        }
    }
}
#pragma warning restore 1591
