#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Wed
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Wed/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.WedModel>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Wed\Detail.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutWed.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 205), Tuple.Create("\"", 239)
, Tuple.Create(Tuple.Create("", 211), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/title_w.png")
, 211), false)
);

WriteLiteral("/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 405), Tuple.Create("\"", 436)
, Tuple.Create(Tuple.Create("", 411), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 411), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 523), Tuple.Create("\"", 557)
            
            #line 15 "..\..\Views\Wed\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 530), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 530), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 587), Tuple.Create("\"", 624)
, Tuple.Create(Tuple.Create("", 593), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 593), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Wed\Detail.cshtml"
           Write(Html.ActionLink("服务范围","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 700), Tuple.Create("\"", 737)
, Tuple.Create(Tuple.Create("", 706), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 706), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Wed\Detail.cshtml"
           Write(Html.ActionLink("高端婚庆策划","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Wed\Detail.cshtml"
               Write(Html.ActionLink("高端婚庆策划","Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Views\Wed\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Wed\Detail.cshtml"
                     foreach (var item in Model.Weds)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1271), Tuple.Create("\"", 1327)
            
            #line 31 "..\..\Views\Wed\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1278), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "Wed", new { id = item.ID})
            
            #line default
            #line hidden
, 1278), false)
);

WriteLiteral(">");

            
            #line 31 "..\..\Views\Wed\Detail.cshtml"
                                                                                                           Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 33 "..\..\Views\Wed\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_wed_detail_body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_wed_detail_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Views\Wed\Detail.cshtml"
                   Write(Model.Wed.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <hr />\r\n                    <di" +
"v");

WriteLiteral(" class=\"yc_wed_detail_body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Views\Wed\Detail.cshtml"
                   Write(Html.DisplayTextFor(t => t.Wed.NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
"     <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
