#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.ManagerMent
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 2 "..\..\Views\ManagerMent\Manager.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ManagerMent/Manager.cshtml")]
    public partial class Manager : System.Web.Mvc.WebViewPage<MvcCarManagerment.Models.ManagerModel>
    {
        public Manager()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\ManagerMent\Manager.cshtml"
  
    ViewBag.Title = "后台信息发布";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\ManagerMent\Manager.cshtml"
 using (Html.BeginForm())
{

            
            #line default
            #line hidden
WriteLiteral("    <table>\r\n        <tr>\r\n            <td>");

            
            #line 10 "..\..\Views\ManagerMent\Manager.cshtml"
           Write(Html.LabelFor(entity => entity.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>");

            
            #line 12 "..\..\Views\ManagerMent\Manager.cshtml"
           Write(Html.DropDownListFor(entity => entity.Title, new SelectList(Basicinfo.GeTypeList(), "ID", "Name")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 16 "..\..\Views\ManagerMent\Manager.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
