#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Pledge
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 2 "..\..\Views\Pledge\Detail.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pledge/Detail.cshtml")]
    public partial class Detail : System.Web.Mvc.WebViewPage<YuanChen.Model.News>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Pledge\Detail.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Pledge\Detail.cshtml"
  
    var list = Basicinfo.GetTopListPledge();

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 274), Tuple.Create("\"", 311)
, Tuple.Create(Tuple.Create("", 280), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/news_title.png")
, 280), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 478), Tuple.Create("\"", 509)
, Tuple.Create(Tuple.Create("", 484), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 484), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 596), Tuple.Create("\"", 630)
            
            #line 18 "..\..\Views\Pledge\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 603), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 603), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 660), Tuple.Create("\"", 697)
, Tuple.Create(Tuple.Create("", 666), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 666), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 721), Tuple.Create("\"", 754)
            
            #line 20 "..\..\Views\Pledge\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 728), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Wed")
            
            #line default
            #line hidden
, 728), false)
);

WriteLiteral(">服务范围</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 786), Tuple.Create("\"", 823)
, Tuple.Create(Tuple.Create("", 792), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 792), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 847), Tuple.Create("\"", 883)
            
            #line 22 "..\..\Views\Pledge\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 854), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Pledge")
            
            #line default
            #line hidden
, 854), false)
);

WriteLiteral(">车辆抵押</a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\Pledge\Detail.cshtml"
               Write(Html.ActionLink("车辆抵押", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Pledge\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Pledge\Detail.cshtml"
                     if (list != null && list.Count > 0)
                    {

                        foreach (var item in list)
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">●</i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1454), Tuple.Create("\"", 1514)
            
            #line 37 "..\..\Views\Pledge\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1461), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "Pledge", new { id = item.ID })
            
            #line default
            #line hidden
, 1461), false)
);

WriteLiteral(">");

            
            #line 37 "..\..\Views\Pledge\Detail.cshtml"
                                                                                                               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 39 "..\..\Views\Pledge\Detail.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_detail_right_body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_detail_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 46 "..\..\Views\Pledge\Detail.cshtml"
                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_detail_time\"");

WriteLiteral(">\r\n                       发布时间： ");

            
            #line 49 "..\..\Views\Pledge\Detail.cshtml"
                        Write(Model.Time.Value.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 51 "..\..\Views\Pledge\Detail.cshtml"
               Write(Html.DisplayTextFor(t => t.NewsComment));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">\r\n                .</div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
