#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Pledge
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pledge/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.NewsListViewModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Pledge\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"yc_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"yc_about_title\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 221), Tuple.Create("\"", 257)
, Tuple.Create(Tuple.Create("", 227), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/carserver.png")
, 227), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"yc_about_content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_about_content_nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_about_content_home\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 424), Tuple.Create("\"", 455)
, Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/home.png")
, 430), false)
);

WriteLiteral(" class=\"yc_about_home_img\"");

WriteLiteral(" /><i");

WriteLiteral(" class=\"yc_about_current\"");

WriteLiteral(">当前位置：</i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 542), Tuple.Create("\"", 576)
            
            #line 14 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 549), false)
);

WriteLiteral(">首页</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 606), Tuple.Create("\"", 643)
, Tuple.Create(Tuple.Create("", 612), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 612), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 667), Tuple.Create("\"", 700)
            
            #line 16 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 674), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Wed")
            
            #line default
            #line hidden
, 674), false)
);

WriteLiteral(">服务范围</a>\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 732), Tuple.Create("\"", 769)
, Tuple.Create(Tuple.Create("", 738), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/list_arrow.png")
, 738), false)
);

WriteLiteral(" />\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 793), Tuple.Create("\"", 829)
            
            #line 18 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 800), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Pledge")
            
            #line default
            #line hidden
, 800), false)
);

WriteLiteral(">车辆抵押</a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"yc_news\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_news_left yc_pledge_left\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_news_right_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Pledge\Index.cshtml"
               Write(Html.ActionLink("车辆抵押", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_news_right_child\"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Views\Pledge\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Pledge\Index.cshtml"
                     foreach (var item in Model.News)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"yc_news_right_2\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"i_nomal\"");

WriteLiteral(">></i><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1331), Tuple.Create("\"", 1391)
            
            #line 30 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1338), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", "Pledge", new { id = item.ID })
            
            #line default
            #line hidden
, 1338), false)
);

WriteLiteral(">");

            
            #line 30 "..\..\Views\Pledge\Index.cshtml"
                                                                                                               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");

            
            #line 32 "..\..\Views\Pledge\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"yc_news_right yc_pledge_right\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_car_right_body\"");

WriteLiteral(">\r\n                    <ul>\r\n");

            
            #line 38 "..\..\Views\Pledge\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Pledge\Index.cshtml"
                         foreach (var news in Model.News)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <div");

WriteLiteral(" class=\"yc_wed_container\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"yc_car_body\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"yc_wed_img\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2000), Tuple.Create("\"", 2050)
            
            #line 44 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2007), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", new { id = news.ID })
            
            #line default
            #line hidden
, 2007), false)
);

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2106), Tuple.Create("\"", 2139)
            
            #line 45 "..\..\Views\Pledge\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2112), Tuple.Create<System.Object, System.Int32>(Url.Content(news.ImageUrl)
            
            #line default
            #line hidden
, 2112), false)
);

WriteLiteral(" style=\"width:178px;height:138px;\"");

WriteLiteral(" /></a>\r\n                                        </div>\r\n                        " +
"                <div");

WriteLiteral(" class=\"yc_wed_content\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"yc_car_content_title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 49 "..\..\Views\Pledge\Index.cshtml"
                                           Write(Html.ActionLink(news.Title, "Detail", new { id = news.ID }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </div>\r\n                           " +
"             </div>\r\n                                    </div>\r\n               " +
"                 </div>\r\n                            </li>\r\n");

            
            #line 55 "..\..\Views\Pledge\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                    <div");

WriteLiteral(" class=\"yc_about_clear\"");

WriteLiteral(">.</div>\r\n                    </div>\r\n\r\n\r\n                    <div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 62 "..\..\Views\Pledge\Index.cshtml"
                   Write(Html.PageLinks(Model.NewsInfo, x => Url.Action("Index", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                \r\n       " +
"     </div>\r\n            \r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
