#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.CarServiceManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/CarServiceManager/IndexList.cshtml")]
    public partial class IndexList : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.ServerListListViewModel>
    {
        public IndexList()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
  
    ViewBag.Title = "IndexList";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    th\r\n    {\r\n        text-align: center;\r\n    }\r\n</style>\r\n<h2");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">\r\n    高端汽车服务列表</h2>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
Write(Html.ActionLink("增加服务类别", "CreateType"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<div");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>\r\n                    类" +
" 型 名 称\r\n                </th>\r\n                <th>\r\n                    操 作\r\n  " +
"              </th>\r\n            </tr>\r\n        </thead>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
        
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
         foreach (var item in Model.ServiceListInfo)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.HiddenFor(modelItem => item.ListID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.HiddenFor(modelItem => item.ParentID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.DisplayFor(modelItem => item.ListName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.ActionLink("编辑类型", "EditType", new { id = item.ListID }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.ActionLink("查看详细", "Details", new { id = item.ListID, parentid = item.ParentID }));

            
            #line default
            #line hidden
WriteLiteral("|\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
               Write(Html.ActionLink("删除类型", "DeleteType", new { id = item.ListID, parentid = item.ParentID }, new { onclick = "return confirm('请确认是否要删除这类型及该类型下的内容?');" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n</div>\r\n<div");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 48 "..\..\Areas\Admin\Views\CarServiceManager\IndexList.cshtml"
Write(Html.PageLinks(Model.NewsInfo, x => Url.Action("IndexList", new { page = x })));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
