#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_ADImageIndex.cshtml")]
    public partial class ADImageIndex : System.Web.Mvc.WebViewPage<MvcCarManagerment.Areas.Admin.Models.ImagesListViewModel>
    {
        public ADImageIndex()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
  
    int image_num = 0;
    var imagesList = Model.Images.ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" style=\"width: 100%; border: 1px; text-align: center;\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
     for (int i = 0; i < 6; i++)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
             for (; image_num < imagesList.Count; image_num++)
            {
                var item = imagesList[image_num];
                i++; if (i == 4) { break; }

            
            #line default
            #line hidden
WriteLiteral("                <td>\r\n                    <table>\r\n                        <tr>\r\n" +
"                            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                图像标题12121： 【");

            
            #line 18 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
                                       Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("】\r\n                            </td>\r\n                        </tr>\r\n            " +
"            <tr>\r\n                            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=");

WriteLiteral(" \"");

            
            #line 23 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
                                      Write(Url.Content(@item.ImagerUrl));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width:150px; height:100px; border:0px;\" alt=\"");

            
            #line 23 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
                                                                                                                         Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            </td>\r\n                        </tr>\r\n          " +
"              <tr>\r\n                            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 29 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
                           Write(Html.ActionLink("删除", "Delete", new { id = item.ID }, new { onclick = "return confirm('是否删除该图片');" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </table>\r\n                </td>\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Shared\_ADImageIndex.cshtml"
     
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");

        }
    }
}
#pragma warning restore 1591
