#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Areas.Admin.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
    using MvcCarManagerment.Service;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml")]
    public partial class LayoutAdmin : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LayoutAdmin()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 184), Tuple.Create("\"", 204)
, Tuple.Create(Tuple.Create("", 191), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 191), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>远辰汽车服务公司后台管理系统</title>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Styles.Render("~/Areas/Admin/Content/bootstrap/css/bootstrap.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Styles.Render("~/Areas/Admin/Content/bootstrap/css/bootstrap-responsive.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Styles.Render("~/Areas/Admin/Content/font-awesome/css/font-awesome.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Styles.Render("~/Areas/Admin/Content/theme.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Styles.Render("~/Areas/Admin/Content/site.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Scripts.Render("~/Areas/Admin/bundles/jquery-1.8.1.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Scripts.Render("~/Areas/Admin/bundles/bootstrap/bootstrap.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Scripts.Render("~/Areas/Admin/bundles/jquery.jqplot.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"navbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"navbar-inner\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav pull-right\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" id=\"fat-menu\"");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"drop3\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral("\r\n                        data-toggle=\"dropdown\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-user\"");

WriteLiteral("></i>");

            
            #line 28 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                                                                   Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("<i");

WriteLiteral(" class=\"icon-caret-down\"");

WriteLiteral("></i></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <li><a");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" href=\"/Home\"");

WriteLiteral(">返回首页</a></li>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                             using (Html.BeginForm("LogOff", "Logion", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                                                        

            
            #line default
            #line hidden
WriteLiteral("                                <li><a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(">注销</a></li>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </li>\r\n                </ul>\r\n" +
"                <a");

WriteLiteral(" class=\"brand\"");

WriteLiteral(" href=\"/Admin/\"");

WriteLiteral("><span");

WriteLiteral(" class=\"first\"");

WriteLiteral(">远辰汽车服务公司后台管理系统</span></a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <" +
"div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"span3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"sidebar-nav\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"icon-th-list\"");

WriteLiteral("></i>栏目信息管理\r\n                    </div>\r\n                    <ul");

WriteLiteral(" id=\"dashboard-menu\"");

WriteLiteral(" class=\"nav nav-list collapse in\"");

WriteLiteral(">\r\n                        <li>");

            
            #line 52 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("关于我们", "Index", "AboutManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 53 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("公司新闻", "Index", "NewsManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 54 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("优惠活动", "Index", "OfferManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 55 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("高端婚庆策划", "Index", "WedManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("高端商务礼仪", "Index", "BusinessManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 57 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("高端汽车服务", "IndexList", "CarServiceManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 58 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("车辆订购、按揭", "Index", "CarOrderManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("车辆抵押", "Index", "PledgeManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 60 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("二手车交易、评估", "Index", "HandCarManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 61 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("客户服务", "Index", "CustomerManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 62 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("首页图片管理", "Index", "ImageManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                        <li>");

            
            #line 63 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       Write(Html.ActionLink("广告图片管理", "ADImageIndex", "ImageManager"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n   " +
"         <div");

WriteLiteral(" class=\"span9\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"stats\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"stat\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"number\"");

WriteLiteral(">0</span>信息</p>\r\n                </div>\r\n                <div>\r\n");

WriteLiteral("                    ");

            
            #line 73 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <footer>\r\n " +
"           <hr />\r\n            <p>&copy; 2013 安徽远辰汽车服务公司</p>\r\n        </footer>\r" +
"\n");

WriteLiteral("    ");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 82 "..\..\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
