#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCarManagerment.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcCarManagerment.Areas.Admin.HTMLHelpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LayoutWed.cshtml")]
    public partial class LayoutWed : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LayoutWed()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>远辰汽车服务有限公司</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 188), Tuple.Create("\"", 208)
, Tuple.Create(Tuple.Create("", 195), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 195), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"../../Areas/Admin/Scripts/ueditor/ueditor.all.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"../../Areas/Admin/Scripts/ueditor/ueditor.all.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"../../Areas/Admin/Scripts/ueditor/ueditor.config.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n    <link");

WriteLiteral(" href=\"../../Areas/Admin/Scripts/ueditor/themes/iframe.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    \r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Styles.Render("~/Content/yc_w_site.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Scripts.Render("~/Scripts/jquery.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Scripts.Render("~/Scripts/bootstrap.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1017), Tuple.Create("\"", 1041)
, Tuple.Create(Tuple.Create("", 1023), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/slide.js")
, 1023), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1065), Tuple.Create("\"", 1091)
, Tuple.Create(Tuple.Create("", 1071), Tuple.Create<System.Object, System.Int32>(Href("~/Content/slider.css")
, 1071), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"yc_global_header\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">远辰微博</a> | <a");

WriteLiteral(" href=\"/Logion/\"");

WriteLiteral(">后台登陆</a>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"YC_global_nav\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"yc_bg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"yc_header\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"yc_logo\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1391), Tuple.Create("\"", 1424)
, Tuple.Create(Tuple.Create("", 1397), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/logo_w.png")
, 1397), false)
);

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_nav\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"/Home/Index\"");

WriteLiteral(" class=\"yc_tab first_tab\"");

WriteLiteral("><i>首页</i></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"/AboutUs/Index\"");

WriteLiteral(" class=\"yc_tab\"");

WriteLiteral("><i>关于我们</i></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                       ");

WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"/News/Index\"");

WriteLiteral(" class=\"yc_tab\"");

WriteLiteral("><i>新闻动态</i></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"/Offer/Index\"");

WriteLiteral(" class=\"yc_tab\"");

WriteLiteral("><i>优惠活动</i></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"/Wed/Index\"");

WriteLiteral(" class=\"yc_tab\"");

WriteLiteral(" id=\"yc_wed\"");

WriteLiteral(" onmouseover=\"mopen(\'yc_slide_my\')\"");

WriteLiteral(" onmouseout=\"mclosetime()\"");

WriteLiteral("><i>服务范围</i></a>\r\n                        <div");

WriteLiteral(" id=\"yc_slide_my\"");

WriteLiteral(" onmouseover=\"mcancelclosetime()\"");

WriteLiteral(" onmouseout=\"mclosetime()\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 54 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("高端婚庆策划", "Index", "Wed"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("高端商务礼仪", "Index", "Business"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 56 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("高端汽车服务", "Index", "CarService"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 57 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("车辆订购、按揭", "Index", "CarOrder"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("车辆抵押", "Index", "Pledge"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 59 "..\..\Views\Shared\_LayoutWed.cshtml"
                       Write(Html.ActionLink("二手车交易、评估", "Index", "HandCar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        ");

WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"yc_title current\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <a");

WriteLiteral(" href=\"/Customer/Index\"");

WriteLiteral(" class=\"yc_tab last_tab\"");

WriteLiteral("><i>客户服务</i></a>\r\n                    </div>\r\n                </div>\r\n           " +
"     <div");

WriteLiteral(" class=\"yc_phone\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"yc_phone_num\"");

WriteLiteral(">\r\n                        <i>400-551-9999</i>\r\n                    </div>\r\n     " +
"               <div");

WriteLiteral(" class=\"yc_phone_icon\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4809), Tuple.Create("\"", 4843)
, Tuple.Create(Tuple.Create("", 4815), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/phone_w.png")
, 4815), false)
);

WriteLiteral("/>\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"yc_clear\"");

WriteLiteral(">.</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div>\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 90 "..\..\Views\Shared\_LayoutWed.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <footer>\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">Copyright© 2013 Ahyuanchen.com All Rights reserverd   版权所有    安徽远辰汽车服务有限公司    地址" +
"：合肥市黄山路汇峰大厦1212室</div>\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">建议使用1024*768以上的屏幕分辨率和6.0以上版本的IE来访问本站</div>\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">客服电话: 400-511-99999   传真:0551-688888888</div>\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">备案号：皖ICP备10020997号</div>\r\n    </footer>\r\n");

WriteLiteral("    ");

            
            #line 98 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Scripts.Render("~/Scripts/MySlide.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 99 "..\..\Views\Shared\_LayoutWed.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
